[build]
  functions = "functions"

[[redirects]]
  from = "/api/stedi-eras"
  to = "/.netlify/functions/stedi-eras"
  status = 200

[[redirects]]
  from = "/api/stedi-eligibility"
  to = "/.netlify/functions/stedi-eligibility"
  status = 200

[[redirects]]
  from = "/api/stedi-claim-status"
  to = "/.netlify/functions/stedi-claim-status"
  status = 200

[functions]
  node_bundler = "esbuild"
